(define (make-from-mag-ang a r)
  (define (dispatch op)
    (cond ((eq? op 'real-part)
           (* a (cos r) ))
          ((eq? op 'imag-part)
           (* a (sin r)))
          ((eq? 'magnitude) a)
          ((eq? 'angle) r)
          (else (error "Unknown op -- MAKE-FROM-MAG-ANG" op))))
  dispatch)
